version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
cache: packages
build_script:
- cmd: powershell .\build.ps1 -Target Default -Verbosity diagnostic
artifacts:
- path: '*build\*.dll'
  name: Binaries
deploy: off